export const GET_COURSE_REQUEST = 'GET_COURSE_REQUEST'
export const GET_COURSE_SUCCESS = 'GET_COURSE_SUCCESS'
export const GET_COURSE_FAILURE = 'GET_COURSE_FAILURE'

export const POST_COURSE_SUCCESS = 'POST_COURSE_SUCCESS'